#! /bin/sh

## My general shell rc file.
# This file will typically be sourced by all my POSIX compliant shells.

## Set up my enviornment variables

### DEFAULT APPS
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

export LESSHISTFILE="$HOME/.local/share/less/hst"
export PAGER=/usr/bin/less

### The following should add the local gems into PATH
RUBY_VER="$(ruby -v | cut -d' ' -f2 | cut -d. -f1,2).0"
export PATH="$HOME/.gem/ruby/$RUBY_VER/bin:$PATH"
unset RUBY_VER

### Add the cargo bin directory to PATH
export PATH="$HOME/.local/bin/cargo:$PATH"

## Custom functions
FUNCTIONS_DIR="$HOME/.config/sh/functions"
. "$FUNCTIONS_DIR/battery" -q
. "$FUNCTIONS_DIR/spell-check"
. "$FUNCTIONS_DIR/mount_for_me"
. "$FUNCTIONS_DIR/newsboat"
unset FUNCTIONS_DIR

## Bookmarks
. "$HOME/.config/sh/bookmarks"

## ssh-agent
. $HOME/.cache/ssh/agent

## Zoom Home
export ZOOM_HOME="${HOME}/.local/share/zoomus"
